name: Build and test
on: push

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.10.7]
        poetry-version: [1.2.0a2]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - run: pipx install poetry==${{ matrix.poetry-version }}
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - run: poetry install
      - run: poetry run pytest .